---
- name: Create file system on extra volume device
  filesystem:
    fstype: "{{ item.filesystem }}"
    dev: "{{ item.device }}"
    force: "{{ item.force|default(omit) }}"
    opts: "{{ item.mkfs_opts|default(None) }} -L {{ item.label }}"
  with_items: "{{ container_runtime_extra_storage }}"
  when:
    - 'item.label|length<=12'
    - 'item.path not in "{{ ansible_mounts }}"'


- name: Create mount entry for extra volume
  mount:
    path: "{{ item.path }}"
    src: "LABEL={{ item.label }}"
    fstype: "{{ item.filesystem }}"
    opts: "{{ item.options|default(omit) }}"
    state: mounted
  with_items: "{{ container_runtime_extra_storage }}"
  when:
    - 'item.label|length<=12'
    - 'item.path not in "{{ ansible_mounts }}"'

